import { supabase } from '@/lib/supabase';
import type { Guest } from '@/types';

/**
 * Auto-generates airport pickup and dropoff driver task suggestions
 * when a guest is placed at a location.
 *
 * Silently swallows errors — the driver_tasks table may not exist in all
 * environments, and task generation is best-effort.
 */
export async function autoGenerateDriverTasks(
  guest: Guest,
  locationName: string,
  departmentName: string,
): Promise<void> {
  try {
    // ── Arrival → Pickup suggestion ───────────────────────────────────────────
    const arrivalDate = guest.arrivalTime?.substring(0, 10);
    const arrivalTime = guest.arrivalTime
      ? guest.arrivalTime.includes('T')
        ? guest.arrivalTime.substring(11, 16)   // HH:MM from ISO datetime
        : undefined
      : undefined;

    if (arrivalDate) {
      const { data: existingPickup } = await supabase
        .from('driver_tasks')
        .select('id')
        .eq('guest_id', guest.id)
        .eq('task_type', 'airport_pickup')
        .maybeSingle();

      if (!existingPickup) {
        const pickupLoc = [guest.arrivalAirport, guest.arrivalTerminal]
          .filter(Boolean).join(' ') || 'Airport';

        await supabase.from('driver_tasks').insert({
          task_type:        'airport_pickup',
          guest_id:         guest.id,
          guest_name:       guest.fullName,
          guest_reference:  guest.referenceNumber,
          pickup_location:  pickupLoc,
          dropoff_location: locationName,
          scheduled_date:   arrivalDate,
          scheduled_time:   arrivalTime ?? null,
          flight_number:    guest.arrivalFlightNumber ?? null,
          airport:          guest.arrivalAirport ?? null,
          terminal:         guest.arrivalTerminal ?? null,
          passenger_count:  1,
          status:           'suggested',
          is_suggestion:    true,
          location:         locationName,
          department:       departmentName,
        });
      }
    }

    // ── Departure → Drop-off suggestion ──────────────────────────────────────
    const departureDate = guest.departureTime?.substring(0, 10);
    const departureTime = guest.departureTime
      ? guest.departureTime.includes('T')
        ? guest.departureTime.substring(11, 16)
        : undefined
      : undefined;

    if (departureDate) {
      const { data: existingDropoff } = await supabase
        .from('driver_tasks')
        .select('id')
        .eq('guest_id', guest.id)
        .eq('task_type', 'airport_dropoff')
        .maybeSingle();

      if (!existingDropoff) {
        const dropoffLoc = [guest.departureAirport, guest.departureTerminal]
          .filter(Boolean).join(' ') || 'Airport';

        await supabase.from('driver_tasks').insert({
          task_type:        'airport_dropoff',
          guest_id:         guest.id,
          guest_name:       guest.fullName,
          guest_reference:  guest.referenceNumber,
          pickup_location:  locationName,
          dropoff_location: dropoffLoc,
          scheduled_date:   departureDate,
          scheduled_time:   departureTime ?? null,
          flight_number:    guest.departureFlightNumber ?? null,
          airport:          guest.departureAirport ?? null,
          terminal:         guest.departureTerminal ?? null,
          passenger_count:  1,
          status:           'suggested',
          is_suggestion:    true,
          location:         locationName,
          department:       departmentName,
        });
      }
    }
  } catch {
    // Best-effort — never block the placement flow
  }
}

/**
 * Auto-generates a mulaqat_transport driver task suggestion
 * when a delegation is assigned to a Mulaqat slot.
 */
export async function autoGenerateMulaqatTask(opts: {
  delegationId: string;
  country: string;
  memberCount: number;
  slotDate: string | null;
  locationName: string;
  departmentName?: string;
}): Promise<void> {
  const { delegationId, country, memberCount, slotDate, locationName, departmentName } = opts;
  if (!slotDate) return;

  try {
    // Check if suggestion already exists for this delegation
    const { data: existing } = await supabase
      .from('driver_tasks')
      .select('id')
      .eq('delegation_id', delegationId)
      .eq('task_type', 'mulaqat_transport')
      .eq('status', 'suggested')
      .maybeSingle();

    if (existing) return;

    await supabase.from('driver_tasks').insert({
      task_type:         'mulaqat_transport',
      delegation_id:     delegationId,
      delegation_country: country,
      guest_name:        `${country} Delegation`,
      pickup_location:   locationName,
      dropoff_location:  'Mulaqat Venue',
      scheduled_date:    slotDate,
      passenger_count:   memberCount || 1,
      status:            'suggested',
      is_suggestion:     true,
      location:          locationName,
      department:        departmentName ?? null,
      notes:             'Auto-generated from Mulaqat slot assignment',
    });
  } catch {
    // Best-effort
  }
}
