import { supabase } from '@/lib/supabase';
import type { Guest, DriverTaskPriority } from '@/types';

// ── priority helpers ──────────────────────────────────────────────────────────

/**
 * Compute auto-priority for a task:
 * - VIP  → guest designation contains "National Amir" or "Nazir"
 * - Urgent → task is within 2 hours from now
 * - Normal → everything else
 */
export function getAutoPriority(
  guestDesignation?: string,
  scheduledDate?: string,
  scheduledTime?: string,
): DriverTaskPriority {
  if (guestDesignation) {
    const d = guestDesignation.toLowerCase();
    if (d.includes('national amir') || d.includes('nazir')) return 'vip';
  }
  if (scheduledDate && scheduledTime) {
    const taskMs  = new Date(`${scheduledDate}T${scheduledTime}:00`).getTime();
    const nowMs   = Date.now();
    const diffHrs = (taskMs - nowMs) / 3_600_000;
    if (diffHrs >= 0 && diffHrs <= 2) return 'urgent';
  }
  return 'normal';
}

// ── batch pickup helpers ──────────────────────────────────────────────────────

/**
 * Find an existing suggested airport_pickup task for the same flight + date + location.
 * Returns the task row (id, passenger_count) or null.
 */
async function findExistingFlightTask(
  taskType: 'airport_pickup' | 'airport_dropoff',
  flightNumber: string,
  scheduledDate: string,
  locationName: string,
) {
  const { data } = await supabase
    .from('driver_tasks')
    .select('id, passenger_count, guest_name')
    .eq('task_type', taskType)
    .eq('flight_number', flightNumber)
    .eq('scheduled_date', scheduledDate)
    .eq('location', locationName)
    .eq('is_suggestion', true)
    .neq('status', 'cancelled')
    .maybeSingle();
  return data as { id: string; passenger_count: number | null; guest_name: string | null } | null;
}

/**
 * Add a passenger record to driver_task_passengers (best-effort).
 */
async function addPassenger(taskId: string, guest: Guest) {
  await supabase.from('driver_task_passengers').insert({
    task_id:    taskId,
    guest_id:   guest.id,
    guest_name: guest.fullName,
    guest_phone: null,
    guest_photo: null,
  });
}

// ── main exports ──────────────────────────────────────────────────────────────

/**
 * Auto-generates airport pickup / drop-off driver task suggestions
 * when a guest is placed at a location.
 *
 * Batch pickup: if another guest on the same flight already has a suggested
 * task, increment passenger_count on that task rather than creating a new one.
 *
 * Priority is auto-assigned based on guest designation and task time.
 *
 * Silently swallows errors — best-effort, never blocks the placement flow.
 */
export async function autoGenerateDriverTasks(
  guest: Guest,
  locationName: string,
  departmentName: string,
): Promise<void> {
  try {
    // ── Arrival → Pickup suggestion ───────────────────────────────────────────
    const arrivalDate = guest.arrivalTime?.substring(0, 10);
    const arrivalTime = guest.arrivalTime?.includes('T')
      ? guest.arrivalTime.substring(11, 16) : undefined;

    if (arrivalDate) {
      const priority = getAutoPriority(
        guest.designation,
        arrivalDate,
        arrivalTime,
      );

      if (guest.arrivalFlightNumber) {
        // Batch: check for an existing task on the same flight
        const existing = await findExistingFlightTask(
          'airport_pickup',
          guest.arrivalFlightNumber,
          arrivalDate,
          locationName,
        );

        if (existing) {
          // Increment passenger count, update guest_name label
          const newCount = (existing.passenger_count ?? 1) + 1;
          await supabase.from('driver_tasks').update({
            passenger_count: newCount,
            guest_name: `${newCount} guests on ${guest.arrivalFlightNumber}`,
          }).eq('id', existing.id);
          await addPassenger(existing.id, guest);
        } else {
          // Check idempotency by guest_id
          const { data: dup } = await supabase
            .from('driver_tasks')
            .select('id')
            .eq('guest_id', guest.id)
            .eq('task_type', 'airport_pickup')
            .maybeSingle();

          if (!dup) {
            const pickupLoc = [guest.arrivalAirport, guest.arrivalTerminal]
              .filter(Boolean).join(' ') || 'Airport';

            const { data: newTask } = await supabase.from('driver_tasks').insert({
              task_type:        'airport_pickup',
              guest_id:         guest.id,
              guest_name:       guest.fullName,
              guest_reference:  guest.referenceNumber,
              pickup_location:  pickupLoc,
              dropoff_location: locationName,
              scheduled_date:   arrivalDate,
              scheduled_time:   arrivalTime ?? null,
              flight_number:    guest.arrivalFlightNumber,
              airport:          guest.arrivalAirport ?? null,
              terminal:         guest.arrivalTerminal ?? null,
              passenger_count:  1,
              priority,
              status:           'suggested',
              is_suggestion:    true,
              location:         locationName,
              department:       departmentName,
            }).select('id').single();

            if (newTask) await addPassenger(newTask.id, guest);
          }
        }
      } else {
        // No flight number — single-guest task (no batching)
        const { data: dup } = await supabase
          .from('driver_tasks').select('id')
          .eq('guest_id', guest.id).eq('task_type', 'airport_pickup').maybeSingle();

        if (!dup) {
          const pickupLoc = [guest.arrivalAirport, guest.arrivalTerminal]
            .filter(Boolean).join(' ') || 'Airport';
          await supabase.from('driver_tasks').insert({
            task_type: 'airport_pickup', guest_id: guest.id,
            guest_name: guest.fullName, guest_reference: guest.referenceNumber,
            pickup_location: pickupLoc, dropoff_location: locationName,
            scheduled_date: arrivalDate, scheduled_time: arrivalTime ?? null,
            airport: guest.arrivalAirport ?? null, terminal: guest.arrivalTerminal ?? null,
            passenger_count: 1, priority, status: 'suggested', is_suggestion: true,
            location: locationName, department: departmentName,
          });
        }
      }
    }

    // ── Departure → Drop-off suggestion ──────────────────────────────────────
    const departureDate = guest.departureTime?.substring(0, 10);
    const departureTime = guest.departureTime?.includes('T')
      ? guest.departureTime.substring(11, 16) : undefined;

    if (departureDate) {
      const priority = getAutoPriority(
        guest.designation,
        departureDate,
        departureTime,
      );

      if (guest.departureFlightNumber) {
        const existing = await findExistingFlightTask(
          'airport_dropoff',
          guest.departureFlightNumber,
          departureDate,
          locationName,
        );

        if (existing) {
          const newCount = (existing.passenger_count ?? 1) + 1;
          await supabase.from('driver_tasks').update({
            passenger_count: newCount,
            guest_name: `${newCount} guests on ${guest.departureFlightNumber}`,
          }).eq('id', existing.id);
          await addPassenger(existing.id, guest);
        } else {
          const { data: dup } = await supabase
            .from('driver_tasks').select('id')
            .eq('guest_id', guest.id).eq('task_type', 'airport_dropoff').maybeSingle();

          if (!dup) {
            const dropoffLoc = [guest.departureAirport, guest.departureTerminal]
              .filter(Boolean).join(' ') || 'Airport';

            const { data: newTask } = await supabase.from('driver_tasks').insert({
              task_type:        'airport_dropoff',
              guest_id:         guest.id,
              guest_name:       guest.fullName,
              guest_reference:  guest.referenceNumber,
              pickup_location:  locationName,
              dropoff_location: dropoffLoc,
              scheduled_date:   departureDate,
              scheduled_time:   departureTime ?? null,
              flight_number:    guest.departureFlightNumber,
              airport:          guest.departureAirport ?? null,
              terminal:         guest.departureTerminal ?? null,
              passenger_count:  1,
              priority,
              status:           'suggested',
              is_suggestion:    true,
              location:         locationName,
              department:       departmentName,
            }).select('id').single();

            if (newTask) await addPassenger(newTask.id, guest);
          }
        }
      } else {
        const { data: dup } = await supabase
          .from('driver_tasks').select('id')
          .eq('guest_id', guest.id).eq('task_type', 'airport_dropoff').maybeSingle();

        if (!dup) {
          const dropoffLoc = [guest.departureAirport, guest.departureTerminal]
            .filter(Boolean).join(' ') || 'Airport';
          await supabase.from('driver_tasks').insert({
            task_type: 'airport_dropoff', guest_id: guest.id,
            guest_name: guest.fullName, guest_reference: guest.referenceNumber,
            pickup_location: locationName, dropoff_location: dropoffLoc,
            scheduled_date: departureDate, scheduled_time: departureTime ?? null,
            airport: guest.departureAirport ?? null, terminal: guest.departureTerminal ?? null,
            passenger_count: 1, priority, status: 'suggested', is_suggestion: true,
            location: locationName, department: departmentName,
          });
        }
      }
    }
  } catch {
    // Best-effort — never block the placement flow
  }
}

/**
 * Auto-generates a mulaqat_transport driver task suggestion
 * when a delegation is assigned to a Mulaqat slot.
 */
export async function autoGenerateMulaqatTask(opts: {
  delegationId: string;
  country: string;
  memberCount: number;
  slotDate: string | null;
  locationName: string;
  departmentName?: string;
}): Promise<void> {
  const { delegationId, country, memberCount, slotDate, locationName, departmentName } = opts;
  if (!slotDate) return;

  try {
    const { data: existing } = await supabase
      .from('driver_tasks')
      .select('id')
      .eq('delegation_id', delegationId)
      .eq('task_type', 'mulaqat_transport')
      .eq('status', 'suggested')
      .maybeSingle();

    if (existing) return;

    await supabase.from('driver_tasks').insert({
      task_type:          'mulaqat_transport',
      delegation_id:      delegationId,
      delegation_country: country,
      guest_name:         `${country} Delegation`,
      pickup_location:    locationName,
      dropoff_location:   'Mulaqat Venue',
      scheduled_date:     slotDate,
      passenger_count:    memberCount || 1,
      priority:           'normal',
      status:             'suggested',
      is_suggestion:      true,
      location:           locationName,
      department:         departmentName ?? null,
      notes:              'Auto-generated from Mulaqat slot assignment',
    });
  } catch {
    // Best-effort
  }
}
