import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { SortableHeader, sortData } from '@/components/SortableHeader';
import { useNavigate } from 'react-router-dom';
import {
  BedDouble, Plus, Pencil, Trash2, MoveRight, UserX,
  LayoutGrid, List, StickyNote, Settings2, Search,
  ChevronDown, ChevronUp, ChevronRight, LogOut, User,
} from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { useGuests } from '@/hooks/useGuests';
import { useRooms } from '@/hooks/useRooms';
import { useDepartments } from '@/hooks/useDepartments';
import { useAuditTrail2 } from '@/hooks/useAuditTrail2';
import { autoGenerateDriverTasks } from '@/lib/driverTaskUtils';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import {
  AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent,
  AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { ProfileDialog } from '@/components/ProfileDialog';
import { SUPER_ADMIN_NAV } from '@/lib/navItems';
import { ROLE_LABELS } from '@/lib/constants';
import type { Block, Room } from '@/types';

// ── Types ─────────────────────────────────────────────────────────────────────

type ViewMode = 'grid' | 'list';
type StatusFilter = 'all' | 'available' | 'partial' | 'full' | 'maintenance' | 'cleaning' | 'reserved';
type RoomStatus = 'available' | 'maintenance' | 'cleaning' | 'reserved';

interface RoomExtras { status: string; notes: string; }
interface MovePending {
  roomId: string; bedNumber: number;
  guestId: string; guestName: string; familyMemberId?: string;
}
type MoveMode = 'same-room' | 'different-room';

// ── Helpers ───────────────────────────────────────────────────────────────────

function occLabel(occupied: number, total: number): 'empty' | 'partial' | 'full' {
  if (occupied === 0) return 'empty';
  if (occupied >= total) return 'full';
  return 'partial';
}

function occBarColor(occupied: number, total: number): string {
  const label = occLabel(occupied, total);
  if (label === 'full') return 'bg-red-500';
  if (label === 'partial') return 'bg-amber-400';
  return 'bg-[#2D5A45]';
}

function progressBarColor(pct: number): string {
  if (pct >= 90) return 'bg-red-500';
  if (pct >= 70) return 'bg-amber-400';
  if (pct >= 1) return 'bg-[#2D5A45]';
  return 'bg-gray-200';
}

function cardBorderClass(occState: 'empty' | 'partial' | 'full', roomStatus: string): string {
  if (roomStatus === 'maintenance') return 'border-gray-300 bg-gray-100';
  if (roomStatus === 'cleaning') return 'border-blue-200 bg-blue-50';
  if (roomStatus === 'reserved') return 'border-purple-200 bg-purple-50';
  if (occState === 'full') return 'border-red-200 bg-white';
  if (occState === 'partial') return 'border-amber-200 bg-white';
  return 'border-green-200 bg-white';
}

function StatusBadge({ status }: { status: string }) {
  if (status === 'maintenance') return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-gray-100 text-gray-600 border border-gray-300">
      🔧 Maintenance
    </span>
  );
  if (status === 'cleaning') return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-blue-50 text-blue-700 border border-blue-200">
      🧹 Cleaning
    </span>
  );
  if (status === 'reserved') return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[10px] font-medium bg-purple-50 text-purple-700 border border-purple-200">
      🔒 Reserved
    </span>
  );
  return null;
}

// ── Room Card ─────────────────────────────────────────────────────────────────

interface RoomCardProps {
  room: Room; blockName: string; occupied: number; total: number;
  roomStatus: string; isExpanded: boolean; onClick: () => void;
}

function RoomCard({ room, blockName, occupied, total, roomStatus, isExpanded, onClick }: RoomCardProps) {
  const state = occLabel(occupied, total);
  const pct = total > 0 ? Math.round((occupied / total) * 100) : 0;
  return (
    <button
      onClick={onClick}
      className={`text-left rounded-xl border-2 p-3 transition-all hover:shadow-md w-full ${cardBorderClass(state, roomStatus)} ${isExpanded ? 'ring-2 ring-[#2D5A45] ring-offset-1' : ''}`}
    >
      <div className="flex items-start justify-between gap-1 mb-1">
        <span className="font-semibold text-sm text-[#1A1A1A] leading-tight">{room.name}</span>
        <StatusBadge status={roomStatus} />
      </div>
      {blockName && <p className="text-xs text-gray-400 mb-2">{blockName}</p>}
      <div className="mb-1.5">
        <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
          <div className={`h-full rounded-full transition-all ${occBarColor(occupied, total)}`} style={{ width: `${pct}%` }} />
        </div>
      </div>
      <p className="text-xs text-[#4A4A4A]">{occupied}/{total} beds</p>
      {(room.availableFrom || room.availableTo) && (
        <p className="text-[10px] text-gray-400 mt-1">
          {room.availableFrom && `From ${room.availableFrom}`}
          {room.availableFrom && room.availableTo && ' · '}
          {room.availableTo && `To ${room.availableTo}`}
        </p>
      )}
    </button>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function AdminRoomsPage() {
  const navigate = useNavigate();
  const { user, logout } = useAuth();
  const { guests } = useGuests();
  const { addEntry: addEntry2 } = useAuditTrail2();
  const {
    rooms, blocks, bedAssignments,
    addBlock, updateBlock, deleteBlock,
    addRoom, updateRoom, deleteRoom,
    assignGuestToRoom, removeGuestFromRoom,
    getOccupancy,
  } = useRooms();
  const {
    departments, departmentList, locationsList,
    getDeptBadgeCls,
  } = useDepartments();

  // ── View state ───────────────────────────────────────────────────────────────

  const [viewMode, setViewMode] = useState<ViewMode>('grid');
  const [deptFilter, setDeptFilter] = useState('all');

  // List-view sort
  const [roomSortCol, setRoomSortCol] = useState<string | null>(null);
  const [roomSortDir, setRoomSortDir] = useState<'asc' | 'desc'>('asc');
  const handleRoomSort = (col: string) => {
    if (roomSortCol === col) setRoomSortDir(d => d === 'asc' ? 'desc' : 'asc');
    else { setRoomSortCol(col); setRoomSortDir('asc'); }
  };
  const [locFilter, setLocFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [search, setSearch] = useState('');
  const [expandedRoomId, setExpandedRoomId] = useState<string | null>(null);
  const [occupancyOpen, setOccupancyOpen] = useState(true);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);

  // ── Room extras (status + notes) ─────────────────────────────────────────────

  const [roomExtras, setRoomExtras] = useState<Record<string, RoomExtras>>({});
  const extrasLoaded = useRef(false);

  const activeRooms = useMemo(() => rooms.filter(r => r.isActive), [rooms]);

  useEffect(() => {
    if (activeRooms.length === 0) return;
    if (extrasLoaded.current) return;
    extrasLoaded.current = true;
    const ids = activeRooms.map(r => r.id);
    supabase.from('rooms').select('id, status, notes').in('id', ids).then(({ data }) => {
      if (!data) return;
      const map: Record<string, RoomExtras> = {};
      for (const row of data) map[row.id] = { status: row.status ?? 'available', notes: row.notes ?? '' };
      setRoomExtras(map);
    });
  }, [activeRooms]);

  // ── Notes editing ────────────────────────────────────────────────────────────

  const [editingNotes, setEditingNotes] = useState(false);
  const [notesDraft, setNotesDraft] = useState('');
  const [addingNotes, setAddingNotes] = useState(false);
  const [addNotesDraft, setAddNotesDraft] = useState('');

  const openEditNotes = () => {
    setNotesDraft(roomExtras[expandedRoomId ?? '']?.notes ?? '');
    setEditingNotes(true);
  };

  const saveNotes = async (roomId: string, notes: string) => {
    await supabase.from('rooms').update({ notes }).eq('id', roomId);
    setRoomExtras(prev => ({ ...prev, [roomId]: { ...prev[roomId] ?? { status: 'available', notes: '' }, notes } }));
    setEditingNotes(false);
    setAddingNotes(false);
  };

  const clearNotes = async (roomId: string) => {
    await supabase.from('rooms').update({ notes: '' }).eq('id', roomId);
    setRoomExtras(prev => ({ ...prev, [roomId]: { ...prev[roomId] ?? { status: 'available', notes: '' }, notes: '' } }));
  };

  const changeRoomStatus = async (roomId: string, newStatus: RoomStatus) => {
    await supabase.from('rooms').update({ status: newStatus }).eq('id', roomId);
    setRoomExtras(prev => ({ ...prev, [roomId]: { ...prev[roomId] ?? { status: 'available', notes: '' }, status: newStatus } }));
    toast.success('Room status updated');
  };

  // ── Dialog state ─────────────────────────────────────────────────────────────

  type DialogMode = 'addRoom' | 'editRoom' | null;
  const [dialogMode, setDialogMode] = useState<DialogMode>(null);
  const [formName, setFormName] = useState('');
  const [formCapacity, setFormCapacity] = useState(2);
  const [formLocationId, setFormLocationId] = useState('');
  const [formBlockId, setFormBlockId] = useState('');
  const [formAvailFrom, setFormAvailFrom] = useState('');
  const [formAvailTo, setFormAvailTo] = useState('');
  const [formError, setFormError] = useState('');
  const [editTarget, setEditTarget] = useState<Room | null>(null);

  // Manage Blocks dialog
  const [manageBlocksOpen, setManageBlocksOpen] = useState(false);
  const [manageBlocksLocId, setManageBlocksLocId] = useState('');
  const [editingBlockId, setEditingBlockId] = useState<string | null>(null);
  const [editingBlockName, setEditingBlockName] = useState('');
  const [addingBlock, setAddingBlock] = useState(false);
  const [newBlockName, setNewBlockName] = useState('');

  // Delete confirmation
  const [deleteType, setDeleteType] = useState<'block' | 'room' | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Block | Room | null>(null);

  // Move guest
  const [movePending, setMovePending] = useState<MovePending | null>(null);
  const [moveMode, setMoveMode] = useState<MoveMode>('same-room');
  const [moveToBedNumber, setMoveToBedNumber] = useState<number>(0);
  const [moveToRoomId, setMoveToRoomId] = useState('');
  const [moveToDiffBed, setMoveToDiffBed] = useState<number>(0);

  // Assign guest to empty bed
  const [assigningBed, setAssigningBed] = useState<{ roomId: string; bedNumber: number } | null>(null);
  const [assignGuestId, setAssignGuestId] = useState('');
  const [assignSearch, setAssignSearch] = useState('');

  // ── Derived maps ──────────────────────────────────────────────────────────────

  // Location name → dept name
  const locToDept = useMemo(() => {
    const m = new Map<string, string>();
    Object.entries(departments).forEach(([dept, locs]) => locs.forEach(l => m.set(l, dept)));
    return m;
  }, [departments]);

  // Location name → location id (for block lookup)
  const locNameToId = useMemo(() => {
    const m = new Map<string, string>();
    locationsList.forEach(l => m.set(l.name, l.id));
    return m;
  }, [locationsList]);

  // Block id → name
  const blockNameMap = useMemo(() => {
    const m: Record<string, string> = {};
    for (const b of blocks) m[b.id] = b.name;
    return m;
  }, [blocks]);

  // Location options for filters (filtered by dept)
  const filteredLocOptions = useMemo(() => {
    if (deptFilter === 'all') {
      const locs = new Set<string>();
      Object.values(departments).forEach(ls => ls.forEach(l => locs.add(l)));
      return Array.from(locs).sort();
    }
    return departments[deptFilter] ?? [];
  }, [deptFilter, departments]);

  // ── Filtered rooms ────────────────────────────────────────────────────────────

  const filteredRooms = useMemo(() => {
    return activeRooms.filter(room => {
      const extras = roomExtras[room.id] ?? { status: 'available', notes: '' };
      const occ = getOccupancy(room.id);
      const oState = occLabel(occ.occupied, occ.total);
      const roomDept = locToDept.get(room.locationId) ?? '';

      if (deptFilter !== 'all' && roomDept !== deptFilter) return false;
      if (locFilter !== 'all' && room.locationId !== locFilter) return false;
      if (statusFilter === 'available' && (oState !== 'empty' || extras.status !== 'available')) return false;
      if (statusFilter === 'partial' && oState !== 'partial') return false;
      if (statusFilter === 'full' && oState !== 'full') return false;
      if (statusFilter === 'maintenance' && extras.status !== 'maintenance') return false;
      if (statusFilter === 'cleaning' && extras.status !== 'cleaning') return false;
      if (statusFilter === 'reserved' && extras.status !== 'reserved') return false;
      if (search.trim()) {
        const q = search.toLowerCase();
        const blockName = room.blockId ? (blockNameMap[room.blockId] ?? '') : '';
        if (!room.name.toLowerCase().includes(q) &&
          !room.locationId.toLowerCase().includes(q) &&
          !blockName.toLowerCase().includes(q) &&
          !roomDept.toLowerCase().includes(q)) return false;
      }
      return true;
    });
  }, [activeRooms, roomExtras, getOccupancy, locToDept, deptFilter, locFilter, statusFilter, search, blockNameMap]);

  // Rooms grouped by dept → location for grid view
  const groupedRooms = useMemo(() => {
    const byLoc: Record<string, Room[]> = {};
    for (const room of filteredRooms) {
      const loc = room.locationId;
      if (!byLoc[loc]) byLoc[loc] = [];
      byLoc[loc].push(room);
    }
    // Build ordered list: dept → location → rooms
    const result: { dept: string; location: string; rooms: Room[] }[] = [];
    for (const dept of departmentList) {
      const locs = departments[dept] ?? [];
      for (const loc of locs) {
        const locRooms = byLoc[loc];
        if (locRooms && locRooms.length > 0) {
          result.push({ dept, location: loc, rooms: locRooms });
        }
      }
    }
    // Any rooms whose location isn't in departments
    for (const [loc, locRooms] of Object.entries(byLoc)) {
      if (!result.some(r => r.location === loc)) {
        result.push({ dept: '', location: loc, rooms: locRooms });
      }
    }
    return result;
  }, [filteredRooms, departments, departmentList]);

  // ── Stats ─────────────────────────────────────────────────────────────────────

  const stats = useMemo(() => {
    const depts = new Set<string>();
    const locs = new Set<string>();
    let totalRooms = 0, totalBeds = 0, occupiedBeds = 0;
    for (const room of activeRooms) {
      const dept = locToDept.get(room.locationId) ?? '';
      if (dept) depts.add(dept);
      locs.add(room.locationId);
      const occ = getOccupancy(room.id);
      totalRooms++;
      totalBeds += occ.total;
      occupiedBeds += occ.occupied;
    }
    return { departments: depts.size, locations: locs.size, totalRooms, totalBeds, occupiedBeds, available: totalBeds - occupiedBeds };
  }, [activeRooms, locToDept, getOccupancy]);

  // Per-location occupancy for overview bars
  const locationOccupancy = useMemo(() => {
    const map: Record<string, { beds: number; occupied: number }> = {};
    for (const room of activeRooms) {
      const loc = room.locationId;
      if (!map[loc]) map[loc] = { beds: 0, occupied: 0 };
      const occ = getOccupancy(room.id);
      map[loc].beds += occ.total;
      map[loc].occupied += occ.occupied;
    }
    return map;
  }, [activeRooms, getOccupancy]);

  // ── Expanded room ─────────────────────────────────────────────────────────────

  const expandedRoom = useMemo(() => activeRooms.find(r => r.id === expandedRoomId) ?? null, [activeRooms, expandedRoomId]);
  const expandedBeds = useMemo(() => expandedRoomId ? (bedAssignments[expandedRoomId] ?? []) : [], [expandedRoomId, bedAssignments]);
  const expandedExtras = useMemo(() => expandedRoomId ? (roomExtras[expandedRoomId] ?? { status: 'available', notes: '' }) : null, [expandedRoomId, roomExtras]);
  const expandedOcc = useMemo(() => expandedRoomId ? getOccupancy(expandedRoomId) : null, [expandedRoomId, getOccupancy]);

  // ── Guest assignment ──────────────────────────────────────────────────────────

  const assignableGuests = useMemo(() =>
    guests.filter(g => !g.roomAssignment && g.status !== 'Accommodated' && (g.status === 'Approved' || !!g.placedLocation)),
    [guests]
  );

  const filteredAssignableGuests = useMemo(() => {
    if (!assignSearch.trim()) return assignableGuests;
    const q = assignSearch.toLowerCase();
    return assignableGuests.filter(g =>
      g.fullName.toLowerCase().includes(q) || g.country.toLowerCase().includes(q)
    );
  }, [assignableGuests, assignSearch]);

  // ── Move dialog computed ──────────────────────────────────────────────────────

  const sameBedOptions = useMemo(() => {
    if (!movePending) return [];
    const beds = bedAssignments[movePending.roomId] ?? [];
    return beds.filter(b => !b.guestName && b.bedNumber !== movePending.bedNumber);
  }, [movePending, bedAssignments]);

  const moveableRooms = useMemo(() => {
    if (!movePending) return [];
    return activeRooms.filter(r => r.id !== movePending.roomId && getOccupancy(r.id).available > 0);
  }, [movePending, activeRooms, getOccupancy]);

  const diffRoomBedOptions = useMemo(() => {
    if (!moveToRoomId) return [];
    return (bedAssignments[moveToRoomId] ?? []).filter(b => !b.guestName);
  }, [moveToRoomId, bedAssignments]);

  // ── Blocks for manage dialog ──────────────────────────────────────────────────

  const manageBlocksLoc = useMemo(() =>
    manageBlocksLocId ? (locationsList.find(l => l.id === manageBlocksLocId) ?? null) : null,
    [manageBlocksLocId, locationsList]
  );

  const manageableBlocks = useMemo(() => {
    if (!manageBlocksLoc) return [];
    return blocks.filter(b => b.locationId === manageBlocksLoc.name);
  }, [blocks, manageBlocksLoc]);

  // Blocks for the current form location
  const formLocationName = useMemo(() => {
    const loc = locationsList.find(l => l.id === formLocationId);
    return loc?.name ?? '';
  }, [formLocationId, locationsList]);

  const formLocationBlocks = useMemo(() =>
    formLocationName ? blocks.filter(b => b.locationId === formLocationName) : [],
    [blocks, formLocationName]
  );

  // ── Handlers ──────────────────────────────────────────────────────────────────

  const openAddRoom = () => {
    setDialogMode('addRoom'); setEditTarget(null);
    setFormName(''); setFormCapacity(2);
    setFormLocationId(locationsList[0]?.id ?? '');
    setFormBlockId(''); setFormAvailFrom(''); setFormAvailTo(''); setFormError('');
  };

  const openEditRoom = (r: Room) => {
    setDialogMode('editRoom'); setEditTarget(r);
    setFormName(r.name); setFormCapacity(r.capacity);
    const locId = locNameToId.get(r.locationId) ?? '';
    setFormLocationId(locId);
    setFormBlockId(r.blockId ?? '');
    setFormAvailFrom(r.availableFrom ?? ''); setFormAvailTo(r.availableTo ?? ''); setFormError('');
  };

  const handleDialogSave = () => {
    const name = formName.trim().replace(/<[^>]*>/g, '');
    if (name.length < 1) { setFormError('Name is required'); return; }
    if (name.length > 60) { setFormError('Name must be 60 characters or fewer'); return; }
    if (!formLocationId) { setFormError('Location is required'); return; }

    if (dialogMode === 'addRoom') {
      if (formCapacity < 1 || formCapacity > 20) { setFormError('Capacity must be 1–20'); return; }
      addRoom(formLocationId, name, formCapacity, formBlockId || undefined, formAvailFrom || undefined, formAvailTo || undefined);
      toast.success('Room added');
    } else if (dialogMode === 'editRoom' && editTarget) {
      const minCap = (bedAssignments[editTarget.id] ?? []).filter(b => !!b.guestName).length;
      if (formCapacity < Math.max(1, minCap)) {
        setFormError(`Capacity cannot be less than current occupancy (${minCap})`); return;
      }
      if (formCapacity > 20) { setFormError('Capacity must be 20 or fewer'); return; }
      updateRoom(editTarget.id, name, formCapacity, formAvailFrom || undefined, formAvailTo || undefined);
      toast.success('Room updated');
    }
    setDialogMode(null);
  };

  const handleDeleteRoom = (r: Room) => {
    const occupied = (bedAssignments[r.id] ?? []).filter(b => !!b.guestName).length;
    if (occupied > 0) { toast.error(`Cannot delete — ${occupied} guest${occupied !== 1 ? 's' : ''} in this room`); return; }
    setDeleteType('room'); setDeleteTarget(r);
  };

  const confirmDelete = () => {
    if (!deleteTarget || !deleteType) return;
    if (deleteType === 'block') deleteBlock(deleteTarget.id);
    else {
      deleteRoom(deleteTarget.id);
      if (deleteTarget.id === expandedRoomId) setExpandedRoomId(null);
    }
    setDeleteTarget(null); setDeleteType(null);
  };

  // Move guest
  const openMoveDialog = (bed: MovePending) => {
    setMovePending(bed); setMoveMode('same-room');
    setMoveToBedNumber(0); setMoveToRoomId(''); setMoveToDiffBed(0);
  };

  const handleConfirmMove = useCallback(() => {
    if (!movePending || !user) return;
    const { roomId, bedNumber, guestId, guestName, familyMemberId } = movePending;
    const sourceRoom = activeRooms.find(r => r.id === roomId);
    const guest = guests.find(g => g.id === guestId);

    if (moveMode === 'same-room') {
      if (!moveToBedNumber) { toast.error('Select a bed'); return; }
      removeGuestFromRoom(roomId, bedNumber);
      assignGuestToRoom(roomId, moveToBedNumber, guestId, guestName, familyMemberId);
      if (guest) {
        addEntry2({
          guestId, guestName, guestReference: guest.referenceNumber,
          locationId: sourceRoom?.locationId ?? '', locationName: sourceRoom?.locationId ?? '',
          departmentId: guest.assignedDepartment ?? '', departmentName: guest.assignedDepartment ?? '',
          type: 'room_change',
          action: `Guest moved within ${sourceRoom?.name ?? roomId}: Bed ${bedNumber} → Bed ${moveToBedNumber}`,
          oldValue: `${sourceRoom?.name} / Bed ${bedNumber}`,
          newValue: `${sourceRoom?.name} / Bed ${moveToBedNumber}`,
          createdBy: { id: user.id, name: user.name, role: 'super-admin' },
          createdAt: new Date().toISOString(),
        });
      }
      toast.success(`${guestName} moved to Bed ${moveToBedNumber}`);
    } else {
      if (!moveToRoomId || !moveToDiffBed) { toast.error('Select a room and bed'); return; }
      const targetRoom = activeRooms.find(r => r.id === moveToRoomId);
      if (!targetRoom) return;
      removeGuestFromRoom(roomId, bedNumber);
      assignGuestToRoom(moveToRoomId, moveToDiffBed, guestId, guestName, familyMemberId);
      if (guest) {
        addEntry2({
          guestId, guestName, guestReference: guest.referenceNumber,
          locationId: sourceRoom?.locationId ?? '', locationName: sourceRoom?.locationId ?? '',
          departmentId: guest.assignedDepartment ?? '', departmentName: guest.assignedDepartment ?? '',
          type: 'room_change',
          action: `Guest moved from ${sourceRoom?.name}/Bed ${bedNumber} to ${targetRoom.name}/Bed ${moveToDiffBed}`,
          oldValue: `${sourceRoom?.name} / Bed ${bedNumber}`,
          newValue: `${targetRoom.name} / Bed ${moveToDiffBed}`,
          createdBy: { id: user.id, name: user.name, role: 'super-admin' },
          createdAt: new Date().toISOString(),
        });
      }
      toast.success(`${guestName} moved to ${targetRoom.name}, Bed ${moveToDiffBed}`);
    }
    setMovePending(null);
  }, [movePending, moveMode, moveToBedNumber, moveToRoomId, moveToDiffBed, user, activeRooms, guests, removeGuestFromRoom, assignGuestToRoom, addEntry2]);

  const handleAssignGuest = () => {
    if (!assigningBed || !assignGuestId) { toast.error('Select a guest'); return; }
    const guest = guests.find(g => g.id === assignGuestId);
    if (!guest) return;
    assignGuestToRoom(assigningBed.roomId, assigningBed.bedNumber, guest.id, guest.fullName);
    toast.success(`${guest.fullName} assigned to Bed ${assigningBed.bedNumber}`);
    // Auto-generate driver task suggestions
    const room = activeRooms.find(r => r.id === assigningBed.roomId);
    autoGenerateDriverTasks(guest, room?.locationId ?? '', guest.assignedDepartment ?? '');
    setAssigningBed(null); setAssignGuestId(''); setAssignSearch('');
  };

  // Block management
  const handleSaveNewBlock = async () => {
    const name = newBlockName.trim();
    if (!name || !manageBlocksLoc) return;
    await addBlock(manageBlocksLocId, name);
    setNewBlockName(''); setAddingBlock(false);
  };

  const handleSaveEditBlock = (blockId: string) => {
    const name = editingBlockName.trim();
    if (!name) return;
    updateBlock(blockId, name);
    setEditingBlockId(null);
  };

  const handleDeleteBlock = (b: Block) => {
    const hasRooms = rooms.some(r => r.blockId === b.id);
    if (hasRooms) { toast.error(`Cannot delete — remove all rooms in ${b.name} first`); return; }
    setDeleteType('block'); setDeleteTarget(b);
  };

  if (!user) return null;

  // ── Status filter options ─────────────────────────────────────────────────────

  const statusOptions: { key: StatusFilter; label: string }[] = [
    { key: 'all', label: 'All' },
    { key: 'available', label: 'Available' },
    { key: 'partial', label: 'Partial' },
    { key: 'full', label: 'Full' },
    { key: 'maintenance', label: 'Maintenance' },
    { key: 'cleaning', label: 'Cleaning' },
    { key: 'reserved', label: 'Reserved' },
  ];

  // ── Render ────────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-[#F5F0E8]">
      <div className="flex">

        {/* ── Sidebar ── */}
        <aside className="w-64 bg-white border-r border-[#E8E3DB] min-h-screen fixed left-0 top-0 z-30">
          <div className="p-4 border-b border-[#E8E3DB]">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-[#2D5A45] rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-lg">J</span>
              </div>
              <div>
                <span className="font-semibold text-[#1A1A1A]">Jalsa Guest</span>
                <p className="text-xs text-[#4A4A4A]">Jalsa Salana UK</p>
              </div>
            </div>
          </div>
          <nav className="p-4 space-y-1">
            <div className="text-xs font-medium text-[#4A4A4A] uppercase tracking-wider mb-2">Main</div>
            {SUPER_ADMIN_NAV.map((item, i) => (
              <button
                key={i}
                onClick={() => navigate(item.href)}
                className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg text-left transition-colors ${
                  item.href === '/admin/rooms'
                    ? 'bg-[#2D5A45] text-white'
                    : 'text-[#4A4A4A] hover:bg-[#F5F0E8]'
                }`}
              >
                <item.icon className="w-5 h-5" />
                {item.label}
              </button>
            ))}
          </nav>
        </aside>

        <main className="flex-1 ml-64">

          {/* ── Header ── */}
          <header className="bg-white border-b border-[#E8E3DB] px-6 py-4 sticky top-0 z-20">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <BedDouble className="w-5 h-5 text-[#2D5A45]" />
                <div>
                  <h1 className="text-xl font-semibold text-[#1A1A1A]">Rooms &amp; Capacity</h1>
                  <p className="text-xs text-[#4A4A4A] mt-0.5">
                    {stats.departments} dept{stats.departments !== 1 ? 's' : ''} · {stats.locations} location{stats.locations !== 1 ? 's' : ''} · {stats.totalRooms} rooms · {stats.totalBeds} total beds · {stats.occupiedBeds} occupied · {stats.available} available
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Button
                  variant="outline"
                  onClick={() => setManageBlocksOpen(true)}
                  className="border-[#D4CFC7] text-[#4A4A4A] h-9 px-4 text-sm flex items-center gap-2"
                >
                  <Settings2 className="w-4 h-4" /> Manage Blocks
                </Button>
                <Button
                  onClick={openAddRoom}
                  className="bg-[#2D5A45] hover:bg-[#234839] text-white h-9 px-4 text-sm flex items-center gap-2"
                >
                  <Plus className="w-4 h-4" /> Add Room
                </Button>
                {/* User menu */}
                <div className="relative">
                  <button
                    onClick={() => setUserMenuOpen(!userMenuOpen)}
                    className="flex items-center gap-2 hover:bg-[#F5F0E8] rounded-lg px-3 py-2 transition-colors"
                  >
                    <div className="w-8 h-8 bg-[#2D5A45] rounded-full flex items-center justify-center text-white font-medium text-sm">
                      {user.name.charAt(0)}
                    </div>
                    <ChevronDown className="w-4 h-4 text-[#4A4A4A]" />
                  </button>
                  {userMenuOpen && (
                    <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-[#E8E3DB] py-1 z-50">
                      <div className="px-4 py-2 border-b border-[#E8E3DB]">
                        <p className="text-sm font-medium text-[#1A1A1A]">{user.name}</p>
                        <p className="text-xs text-[#4A4A4A]">{ROLE_LABELS[user.role]}</p>
                      </div>
                      <button
                        onClick={() => { setUserMenuOpen(false); setProfileOpen(true); }}
                        className="w-full flex items-center gap-2 px-4 py-2 text-sm text-[#1A1A1A] hover:bg-[#F5F0E8]"
                      >
                        <User className="w-4 h-4 text-[#4A4A4A]" /> Profile
                      </button>
                      <button
                        onClick={() => { logout(); navigate('/login'); }}
                        className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50"
                      >
                        <LogOut className="w-4 h-4" /> Sign out
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </header>

          <div className="p-6 space-y-5">

            {/* ── Filter Row ── */}
            <div className="bg-white rounded-xl border border-[#E8E3DB] p-4 flex flex-wrap items-center gap-3">
              {/* Department filter */}
              <select
                value={deptFilter}
                onChange={e => { setDeptFilter(e.target.value); setLocFilter('all'); }}
                className="px-3 py-1.5 border border-[#D4CFC7] rounded-lg text-sm bg-white focus:border-[#2D5A45] focus:outline-none h-9"
              >
                <option value="all">All Departments</option>
                {departmentList.map(d => <option key={d} value={d}>{d}</option>)}
              </select>

              {/* Location filter */}
              <select
                value={locFilter}
                onChange={e => setLocFilter(e.target.value)}
                className="px-3 py-1.5 border border-[#D4CFC7] rounded-lg text-sm bg-white focus:border-[#2D5A45] focus:outline-none h-9"
              >
                <option value="all">All Locations</option>
                {filteredLocOptions.map(l => <option key={l} value={l}>{l}</option>)}
              </select>

              {/* Status filter */}
              <div className="flex items-center gap-1 flex-wrap">
                {statusOptions.map(opt => (
                  <button
                    key={opt.key}
                    onClick={() => setStatusFilter(opt.key)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                      statusFilter === opt.key
                        ? 'bg-[#2D5A45] text-white border-[#2D5A45]'
                        : 'bg-white text-[#4A4A4A] border-[#D4CFC7] hover:border-[#2D5A45] hover:text-[#2D5A45]'
                    }`}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>

              {/* View toggle */}
              <div className="flex items-center border border-[#D4CFC7] rounded-lg overflow-hidden ml-auto">
                <button
                  onClick={() => setViewMode('grid')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium transition-colors ${viewMode === 'grid' ? 'bg-[#2D5A45] text-white' : 'bg-white text-[#4A4A4A] hover:bg-[#F5F0E8]'}`}
                >
                  <LayoutGrid className="w-3.5 h-3.5" /> Grid
                </button>
                <button
                  onClick={() => setViewMode('list')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium transition-colors border-l border-[#D4CFC7] ${viewMode === 'list' ? 'bg-[#2D5A45] text-white' : 'bg-white text-[#4A4A4A] hover:bg-[#F5F0E8]'}`}
                >
                  <List className="w-3.5 h-3.5" /> List
                </button>
              </div>

              {/* Search */}
              <div className="relative">
                <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400 pointer-events-none" />
                <Input
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  placeholder="Search rooms..."
                  className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm pl-8 w-48"
                />
              </div>
            </div>

            {/* ── Occupancy Overview ── */}
            <div className="bg-white rounded-xl border border-[#E8E3DB] overflow-hidden">
              <button
                onClick={() => setOccupancyOpen(o => !o)}
                className="w-full flex items-center justify-between px-5 py-3 border-b border-[#E8E3DB] hover:bg-[#F9F8F6] transition-colors"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-semibold text-[#1A1A1A]">📊 Occupancy Overview</span>
                </div>
                {occupancyOpen
                  ? <ChevronUp className="w-4 h-4 text-[#4A4A4A]" />
                  : <ChevronDown className="w-4 h-4 text-[#4A4A4A]" />}
              </button>
              {occupancyOpen && (
                <div className="px-5 py-4 space-y-5">
                  {departmentList.map(dept => {
                    const locs = departments[dept] ?? [];
                    const hasAny = locs.some(loc => locationOccupancy[loc]);
                    if (!hasAny) return null;
                    return (
                      <div key={dept}>
                        <p className={`text-xs font-semibold uppercase tracking-wider mb-2 inline-flex items-center px-2 py-0.5 rounded-full border ${getDeptBadgeCls(dept)}`}>
                          {dept}
                        </p>
                        <div className="space-y-2 pl-2">
                          {locs.map(loc => {
                            const o = locationOccupancy[loc];
                            if (!o) return null;
                            const pct = o.beds > 0 ? Math.round((o.occupied / o.beds) * 100) : 0;
                            return (
                              <div key={loc} className="flex items-center gap-3">
                                <span className="text-sm text-[#4A4A4A] w-40 shrink-0 truncate">{loc}</span>
                                <div className="flex-1 h-2.5 bg-gray-100 rounded-full overflow-hidden">
                                  <div
                                    className={`h-full rounded-full transition-all ${progressBarColor(pct)}`}
                                    style={{ width: `${pct}%` }}
                                  />
                                </div>
                                <span className="text-xs text-[#4A4A4A] w-28 shrink-0">
                                  {o.occupied}/{o.beds} beds ({pct}%)
                                  {pct === 100 && <span className="ml-1 text-red-600 font-semibold">FULL</span>}
                                </span>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                  {departmentList.length === 0 && (
                    <p className="text-sm text-gray-400 text-center py-2">No occupancy data available.</p>
                  )}
                </div>
              )}
            </div>

            {/* ── Room Grid or List ── */}
            {filteredRooms.length === 0 ? (
              <div className="bg-white rounded-xl border border-[#E8E3DB] p-12 text-center">
                <BedDouble className="w-12 h-12 mx-auto mb-4 text-[#D4CFC7]" />
                <p className="text-base font-semibold text-[#1A1A1A] mb-1">No rooms found</p>
                <p className="text-sm text-[#4A4A4A]">Try adjusting your filters or add a room.</p>
              </div>
            ) : viewMode === 'grid' ? (

              /* ── Grid View ── */
              <div className="space-y-6">
                {groupedRooms.map(({ dept, location, rooms: locRooms }) => (
                  <div key={location}>
                    {/* Location header */}
                    <div className="flex items-center gap-3 mb-3">
                      <div className="h-px bg-[#D4CFC7] flex-1" />
                      <span className="text-sm font-semibold text-gray-700 bg-gray-50 rounded-lg px-3 py-1.5 border border-[#E8E3DB] shrink-0">
                        {location}{dept && <span className="text-gray-400 font-normal"> ({dept})</span>}
                      </span>
                      <div className="h-px bg-[#D4CFC7] flex-1" />
                    </div>
                    {/* Room cards */}
                    <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
                      {locRooms.map(room => {
                        const occ = getOccupancy(room.id);
                        const extras = roomExtras[room.id] ?? { status: 'available', notes: '' };
                        const blockName = room.blockId ? (blockNameMap[room.blockId] ?? '') : '';
                        return (
                          <RoomCard
                            key={room.id}
                            room={room}
                            blockName={blockName}
                            occupied={occ.occupied}
                            total={occ.total}
                            roomStatus={extras.status}
                            isExpanded={expandedRoomId === room.id}
                            onClick={() => {
                              setExpandedRoomId(prev => prev === room.id ? null : room.id);
                              setEditingNotes(false); setAddingNotes(false);
                            }}
                          />
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>

            ) : (

              /* ── List View ── */
              <div className="bg-white rounded-xl border border-[#E8E3DB] overflow-hidden">
                <div className="px-5 py-3 border-b border-[#E8E3DB] bg-[#F9F8F6] flex items-center justify-between">
                  <span className="text-sm font-semibold text-[#1A1A1A]">Room List</span>
                  <span className="text-xs text-[#4A4A4A]/60">{filteredRooms.length} rooms</span>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-[#E8E3DB] bg-[#F9F8F6]">
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Department</th>
                        <SortableHeader label="Location" column="locationId" sortCol={roomSortCol} sortDir={roomSortDir} onSort={handleRoomSort} />
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Block</th>
                        <SortableHeader label="Room" column="name" sortCol={roomSortCol} sortDir={roomSortDir} onSort={handleRoomSort} />
                        <SortableHeader label="Cap." column="capacity" sortCol={roomSortCol} sortDir={roomSortDir} onSort={handleRoomSort} />
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Occ.</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Avail.</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Occupancy</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Status</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Dates</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Notes</th>
                        <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-[#E8E3DB]">
                      {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
                      {(sortData(filteredRooms as any[], roomSortCol, roomSortDir) as typeof filteredRooms).map(room => {
                        const dept = locToDept.get(room.locationId) ?? '—';
                        const block = room.blockId ? blocks.find(b => b.id === room.blockId) : null;
                        const occ = getOccupancy(room.id);
                        const extras = roomExtras[room.id] ?? { status: 'available', notes: '' };
                        const pct = occ.total > 0 ? Math.round((occ.occupied / occ.total) * 100) : 0;
                        return (
                          <tr key={room.id} className="hover:bg-[#F9F8F6]">
                            <td className="px-4 py-3">
                              <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${getDeptBadgeCls(dept)}`}>
                                {dept}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-[#1A1A1A] font-medium">{room.locationId}</td>
                            <td className="px-4 py-3 text-[#4A4A4A]">{block?.name ?? <span className="text-gray-400 italic">—</span>}</td>
                            <td className="px-4 py-3 font-semibold text-[#1A1A1A]">{room.name}</td>
                            <td className="px-4 py-3 text-[#4A4A4A] text-center">{occ.total}</td>
                            <td className="px-4 py-3 text-[#4A4A4A] text-center">{occ.occupied}</td>
                            <td className="px-4 py-3 text-[#4A4A4A] text-center">{occ.available}</td>
                            <td className="px-4 py-3">
                              <div className="flex items-center gap-2">
                                <div className="w-20 h-2 bg-gray-200 rounded-full overflow-hidden shrink-0">
                                  <div className={`h-full rounded-full ${progressBarColor(pct)}`} style={{ width: `${pct}%` }} />
                                </div>
                                <span className="text-xs text-[#4A4A4A]">{pct}%</span>
                              </div>
                            </td>
                            <td className="px-4 py-3">
                              {extras.status !== 'available'
                                ? <StatusBadge status={extras.status} />
                                : occ.available === 0 && occ.total > 0
                                  ? <span className="text-xs bg-red-50 text-red-700 border border-red-200 px-2 py-0.5 rounded-full">Full</span>
                                  : occ.occupied === 0
                                    ? <span className="text-xs bg-green-50 text-green-700 border border-green-200 px-2 py-0.5 rounded-full">Empty</span>
                                    : <span className="text-xs bg-amber-50 text-amber-700 border border-amber-200 px-2 py-0.5 rounded-full">Partial</span>}
                            </td>
                            <td className="px-4 py-3 text-xs text-[#4A4A4A] whitespace-nowrap">
                              {room.availableFrom || room.availableTo
                                ? `${room.availableFrom ?? '?'} – ${room.availableTo ?? '?'}`
                                : <span className="text-gray-400 italic">Always</span>}
                            </td>
                            <td className="px-4 py-3 max-w-[160px]">
                              {extras.notes
                                ? <span className="text-xs text-[#4A4A4A] truncate block" title={extras.notes}>{extras.notes}</span>
                                : <span className="text-xs text-gray-400 italic">—</span>}
                            </td>
                            <td className="px-4 py-3">
                              <div className="flex items-center gap-1">
                                <button
                                  onClick={() => {
                                    setExpandedRoomId(prev => prev === room.id ? null : room.id);
                                    setEditingNotes(false); setAddingNotes(false);
                                    setViewMode('grid');
                                  }}
                                  className="inline-flex items-center gap-1 px-2 py-1 rounded text-xs text-[#2D5A45] hover:bg-[#D6E4D9] transition-colors"
                                >
                                  <BedDouble className="w-3 h-3" /> Beds
                                </button>
                                <button
                                  onClick={() => openEditRoom(room)}
                                  className="p-1.5 rounded text-[#4A4A4A] hover:bg-blue-50 hover:text-blue-600 transition-colors"
                                >
                                  <Pencil className="w-3.5 h-3.5" />
                                </button>
                                <button
                                  onClick={() => handleDeleteRoom(room)}
                                  className="p-1.5 rounded text-[#4A4A4A] hover:bg-red-50 hover:text-red-500 transition-colors"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* ── Bed-Level View ── */}
            {expandedRoom && expandedExtras && expandedOcc && (
              <div className="bg-white rounded-xl border border-[#E8E3DB] overflow-hidden">
                {/* Room header */}
                <div className="flex flex-wrap items-center gap-3 px-5 py-4 border-b border-[#E8E3DB] bg-[#F9F8F6]">
                  <div>
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-base text-[#1A1A1A]">{expandedRoom.name}</span>
                      <span className="text-xs text-gray-400">· {expandedRoom.locationId}</span>
                      {expandedRoom.blockId && blockNameMap[expandedRoom.blockId] && (
                        <span className="text-xs text-gray-400">· {blockNameMap[expandedRoom.blockId]}</span>
                      )}
                      <span className="text-xs text-[#4A4A4A]">· {expandedRoom.capacity} beds</span>
                      <StatusBadge status={expandedExtras.status} />
                      {(() => {
                        const dept = locToDept.get(expandedRoom.locationId) ?? '';
                        return dept ? (
                          <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${getDeptBadgeCls(dept)}`}>{dept}</span>
                        ) : null;
                      })()}
                    </div>
                    {(expandedRoom.availableFrom || expandedRoom.availableTo) && (
                      <p className="text-xs text-gray-400 mt-0.5">
                        {expandedRoom.availableFrom && `From ${expandedRoom.availableFrom}`}
                        {expandedRoom.availableFrom && expandedRoom.availableTo && ' · '}
                        {expandedRoom.availableTo && `To ${expandedRoom.availableTo}`}
                      </p>
                    )}
                  </div>
                  <div className="ml-auto flex items-center gap-3">
                    <span className="text-sm text-[#4A4A4A]">
                      <span className="font-semibold text-[#1A1A1A]">{expandedOcc.occupied}</span>/{expandedOcc.total} beds occupied
                    </span>
                    <button
                      onClick={() => setExpandedRoomId(null)}
                      className="text-xs text-gray-400 hover:text-gray-600 transition-colors"
                    >
                      ✕ Close
                    </button>
                  </div>
                </div>

                {/* Notes bar */}
                {expandedExtras.notes && !editingNotes && (
                  <div className="flex items-start gap-3 px-5 py-3 bg-amber-50 border-b border-amber-200">
                    <StickyNote className="w-4 h-4 text-amber-600 mt-0.5 shrink-0" />
                    <p className="text-sm text-amber-800 flex-1">{expandedExtras.notes}</p>
                    <button onClick={openEditNotes} className="text-xs text-amber-700 hover:text-amber-900 font-medium shrink-0">Edit</button>
                    <button onClick={() => clearNotes(expandedRoom.id)} className="text-xs text-amber-700 hover:text-amber-900 font-medium shrink-0">Clear</button>
                  </div>
                )}

                {/* Edit notes inline */}
                {editingNotes && (
                  <div className="px-5 py-3 border-b border-[#E8E3DB] bg-amber-50 space-y-2">
                    <Label className="text-xs text-[#4A4A4A]">Room Notes</Label>
                    <textarea
                      value={notesDraft}
                      onChange={e => setNotesDraft(e.target.value)}
                      rows={3}
                      className="w-full border border-[#D4CFC7] rounded-lg px-3 py-2 text-sm text-[#1A1A1A] focus:outline-none focus:border-[#2D5A45] resize-none"
                      placeholder="Add notes about this room…"
                    />
                    <div className="flex gap-2">
                      <Button onClick={() => saveNotes(expandedRoom.id, notesDraft)} className="bg-[#2D5A45] hover:bg-[#234839] text-white h-8 px-3 text-xs">Save</Button>
                      <Button variant="outline" onClick={() => setEditingNotes(false)} className="border-[#D4CFC7] text-[#4A4A4A] h-8 px-3 text-xs">Cancel</Button>
                    </div>
                  </div>
                )}

                {/* Beds */}
                <div className="px-5 py-4">
                  <div className="flex flex-wrap gap-3">
                    {expandedBeds.map(bed => {
                      const guestData = bed.guestId ? guests.find(g => g.id === bed.guestId) : null;
                      const isAssigning = assigningBed?.roomId === expandedRoom.id && assigningBed.bedNumber === bed.bedNumber;

                      if (bed.guestName) {
                        return (
                          <div key={bed.bedNumber} className="bg-[#D6E4D9] border border-[#2D5A45]/20 rounded-lg p-3 min-w-[140px] max-w-[200px] flex-1">
                            <p className="text-[10px] text-[#4A4A4A] mb-1">Bed {bed.bedNumber}</p>
                            <p className="font-semibold text-sm text-[#1A1A1A] leading-tight">{bed.guestName}</p>
                            {guestData && <p className="text-xs text-[#4A4A4A] mt-0.5">{guestData.country}</p>}
                            {guestData?.arrival_date && <p className="text-[10px] text-gray-400 mt-0.5">Arrival: {guestData.arrival_date}</p>}
                            <div className="flex items-center gap-1.5 mt-2">
                              <button
                                onClick={() => openMoveDialog({ roomId: expandedRoom.id, bedNumber: bed.bedNumber, guestId: bed.guestId!, guestName: bed.guestName!, familyMemberId: bed.familyMemberId })}
                                className="flex items-center gap-1 text-[10px] text-blue-600 hover:text-blue-800 font-medium transition-colors"
                              >
                                <MoveRight className="w-3 h-3" /> Move
                              </button>
                              <span className="text-gray-300">|</span>
                              <button
                                onClick={() => removeGuestFromRoom(expandedRoom.id, bed.bedNumber)}
                                className="text-[10px] text-red-500 hover:text-red-700 font-medium transition-colors flex items-center gap-0.5"
                              >
                                <UserX className="w-3 h-3" /> Remove
                              </button>
                            </div>
                          </div>
                        );
                      }

                      // Empty bed
                      return (
                        <div key={bed.bedNumber} className="bg-gray-50 border border-dashed border-gray-300 rounded-lg p-3 min-w-[140px] max-w-[200px] flex-1">
                          <p className="text-[10px] text-[#4A4A4A] mb-1">Bed {bed.bedNumber}</p>
                          <p className="text-xs text-gray-400 italic mb-2">empty</p>
                          {isAssigning ? (
                            <div className="space-y-1.5">
                              <Input
                                value={assignSearch}
                                onChange={e => setAssignSearch(e.target.value)}
                                placeholder="Search guest…"
                                className="border-[#D4CFC7] focus:border-[#2D5A45] h-7 text-xs"
                              />
                              <select
                                value={assignGuestId}
                                onChange={e => setAssignGuestId(e.target.value)}
                                className="w-full border border-[#D4CFC7] rounded px-2 py-1 text-xs text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45]"
                                size={3}
                              >
                                <option value="">Select guest…</option>
                                {filteredAssignableGuests.map(g => (
                                  <option key={g.id} value={g.id}>{g.fullName} ({g.country})</option>
                                ))}
                              </select>
                              <div className="flex gap-1">
                                <button
                                  onClick={handleAssignGuest}
                                  className="flex-1 text-[10px] font-medium bg-[#2D5A45] text-white rounded px-2 py-1 hover:bg-[#234839] transition-colors"
                                >
                                  Assign
                                </button>
                                <button
                                  onClick={() => { setAssigningBed(null); setAssignGuestId(''); setAssignSearch(''); }}
                                  className="text-[10px] text-gray-500 hover:text-gray-700 px-1"
                                >
                                  ✕
                                </button>
                              </div>
                            </div>
                          ) : (
                            <button
                              onClick={() => { setAssigningBed({ roomId: expandedRoom.id, bedNumber: bed.bedNumber }); setAssignGuestId(''); setAssignSearch(''); }}
                              className="text-[10px] font-medium text-[#2D5A45] hover:underline"
                            >
                              + Assign
                            </button>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Add notes inline */}
                {addingNotes && !editingNotes && (
                  <div className="px-5 pb-4 space-y-2">
                    <Label className="text-xs text-[#4A4A4A]">Add Notes</Label>
                    <textarea
                      value={addNotesDraft}
                      onChange={e => setAddNotesDraft(e.target.value)}
                      rows={3}
                      className="w-full border border-[#D4CFC7] rounded-lg px-3 py-2 text-sm text-[#1A1A1A] focus:outline-none focus:border-[#2D5A45] resize-none"
                      placeholder="Add notes about this room…"
                    />
                    <div className="flex gap-2">
                      <Button onClick={() => { saveNotes(expandedRoom.id, addNotesDraft); setAddNotesDraft(''); }} className="bg-[#2D5A45] hover:bg-[#234839] text-white h-8 px-3 text-xs">Save</Button>
                      <Button variant="outline" onClick={() => { setAddingNotes(false); setAddNotesDraft(''); }} className="border-[#D4CFC7] text-[#4A4A4A] h-8 px-3 text-xs">Cancel</Button>
                    </div>
                  </div>
                )}

                {/* Bottom action row */}
                <div className="flex items-center gap-3 px-5 py-3 border-t border-[#E8E3DB] bg-[#F9F8F6]">
                  <select
                    value={expandedExtras.status}
                    onChange={e => changeRoomStatus(expandedRoom.id, e.target.value as RoomStatus)}
                    className="border border-[#D4CFC7] rounded-lg px-3 py-1.5 text-xs text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45] h-8"
                  >
                    <option value="available">Available</option>
                    <option value="maintenance">Maintenance</option>
                    <option value="cleaning">Cleaning</option>
                    <option value="reserved">Reserved</option>
                  </select>
                  <span className="text-xs text-gray-400">Change Status</span>
                  <div className="flex-1" />
                  <Button variant="outline" onClick={() => openEditRoom(expandedRoom)} className="border-[#D4CFC7] text-[#4A4A4A] h-8 px-3 text-xs flex items-center gap-1.5">
                    <Pencil className="w-3 h-3" /> Edit Room
                  </Button>
                  {!addingNotes && !editingNotes && (
                    <Button
                      variant="outline"
                      onClick={() => { if (expandedExtras.notes) openEditNotes(); else { setAddingNotes(true); setAddNotesDraft(''); } }}
                      className="border-[#D4CFC7] text-[#4A4A4A] h-8 px-3 text-xs flex items-center gap-1.5"
                    >
                      <StickyNote className="w-3 h-3" /> {expandedExtras.notes ? 'Edit Notes' : 'Add Notes'}
                    </Button>
                  )}
                  <Button variant="outline" onClick={() => handleDeleteRoom(expandedRoom)} className="border-red-200 text-red-600 hover:bg-red-50 h-8 px-3 text-xs flex items-center gap-1.5">
                    <Trash2 className="w-3 h-3" /> Delete
                  </Button>
                </div>
              </div>
            )}

          </div>
        </main>
      </div>

      {/* ── Add / Edit Room Dialog ── */}
      <Dialog open={dialogMode !== null} onOpenChange={o => { if (!o) setDialogMode(null); }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="text-[#1A1A1A]">
              {dialogMode === 'addRoom' ? 'Add Room' : 'Edit Room'}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-1">
            {dialogMode === 'addRoom' && (
              <div>
                <Label className="text-xs text-[#4A4A4A] mb-1 block">Location<span className="text-red-500 ml-0.5">*</span></Label>
                <select
                  value={formLocationId}
                  onChange={e => { setFormLocationId(e.target.value); setFormBlockId(''); }}
                  className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45] h-9"
                >
                  <option value="">Select location…</option>
                  {departmentList.map(dept => {
                    const locs = (departments[dept] ?? []).map(ln => locationsList.find(l => l.name === ln)).filter(Boolean);
                    if (locs.length === 0) return null;
                    return (
                      <optgroup key={dept} label={`── ${dept} ──`}>
                        {locs.map(l => l && <option key={l.id} value={l.id}>{l.name}</option>)}
                      </optgroup>
                    );
                  })}
                </select>
              </div>
            )}
            <div>
              <Label className="text-xs text-[#4A4A4A] mb-1 block">Room Name<span className="text-red-500 ml-0.5">*</span></Label>
              <Input
                value={formName}
                onChange={e => { setFormName(e.target.value); setFormError(''); }}
                placeholder="e.g. A-104"
                className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm"
                maxLength={60}
              />
            </div>
            <div>
              <Label className="text-xs text-[#4A4A4A] mb-1 block">Capacity (beds)<span className="text-red-500 ml-0.5">*</span></Label>
              <Input
                type="number" min={1} max={20}
                value={formCapacity}
                onChange={e => { setFormCapacity(Number(e.target.value)); setFormError(''); }}
                className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm"
              />
            </div>
            {formLocationBlocks.length > 0 && (
              <div>
                <Label className="text-xs text-[#4A4A4A] mb-1 block">Block (optional)</Label>
                <select
                  value={formBlockId}
                  onChange={e => setFormBlockId(e.target.value)}
                  className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45] h-9"
                >
                  <option value="">No Block</option>
                  {formLocationBlocks.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
                </select>
              </div>
            )}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <Label className="text-xs text-[#4A4A4A] mb-1 block">Available From</Label>
                <Input type="date" value={formAvailFrom} onChange={e => setFormAvailFrom(e.target.value)} className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm" />
              </div>
              <div>
                <Label className="text-xs text-[#4A4A4A] mb-1 block">Available To</Label>
                <Input type="date" value={formAvailTo} onChange={e => setFormAvailTo(e.target.value)} className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm" />
              </div>
            </div>
            <p className="text-xs text-gray-400">Leave dates blank if always available.</p>
            {formError && <p className="text-xs text-red-600">{formError}</p>}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogMode(null)} className="border-[#D4CFC7] text-[#4A4A4A] h-9 text-sm">Cancel</Button>
            <Button onClick={handleDialogSave} className="bg-[#2D5A45] hover:bg-[#234839] text-white h-9 text-sm">
              {dialogMode === 'editRoom' ? 'Save Changes' : 'Add Room'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Delete Confirmation ── */}
      <AlertDialog open={!!deleteTarget} onOpenChange={o => { if (!o) { setDeleteTarget(null); setDeleteType(null); } }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {deleteType === 'block' ? 'Block' : 'Room'}</AlertDialogTitle>
            <AlertDialogDescription>Delete <strong>{deleteTarget?.name}</strong>? This cannot be undone.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={confirmDelete} className="bg-red-600 hover:bg-red-700 text-white">Delete</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* ── Move Guest Dialog ── */}
      <Dialog open={!!movePending} onOpenChange={o => { if (!o) setMovePending(null); }}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="text-[#1A1A1A]">Move Guest — {movePending?.guestName}</DialogTitle>
          </DialogHeader>
          <div className="py-2 space-y-4">
            <div className="space-y-2">
              <label className="flex items-center gap-3 cursor-pointer p-3 rounded-lg border border-[#E8E3DB] hover:border-[#2D5A45] transition-colors">
                <input type="radio" name="moveMode" value="same-room" checked={moveMode === 'same-room'}
                  onChange={() => { setMoveMode('same-room'); setMoveToBedNumber(0); }} className="accent-[#2D5A45]" />
                <div>
                  <p className="text-sm font-medium text-[#1A1A1A]">Same room — different bed</p>
                  <p className="text-xs text-gray-400">Move within the same room</p>
                </div>
              </label>
              <label className="flex items-center gap-3 cursor-pointer p-3 rounded-lg border border-[#E8E3DB] hover:border-[#2D5A45] transition-colors">
                <input type="radio" name="moveMode" value="different-room" checked={moveMode === 'different-room'}
                  onChange={() => { setMoveMode('different-room'); setMoveToRoomId(''); setMoveToDiffBed(0); }} className="accent-[#2D5A45]" />
                <div>
                  <p className="text-sm font-medium text-[#1A1A1A]">Different room</p>
                  <p className="text-xs text-gray-400">Move to any room across all locations</p>
                </div>
              </label>
            </div>

            {moveMode === 'same-room' && (
              <div>
                <Label className="text-xs text-[#4A4A4A] mb-1 block">Select bed</Label>
                <select
                  value={moveToBedNumber}
                  onChange={e => setMoveToBedNumber(Number(e.target.value))}
                  className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45]"
                >
                  <option value={0}>Select bed…</option>
                  {sameBedOptions.map(b => <option key={b.bedNumber} value={b.bedNumber}>Bed {b.bedNumber}</option>)}
                </select>
                {sameBedOptions.length === 0 && <p className="text-xs text-amber-600 mt-1">No other available beds in this room.</p>}
              </div>
            )}

            {moveMode === 'different-room' && (
              <div className="space-y-3">
                <div>
                  <Label className="text-xs text-[#4A4A4A] mb-1 block">Select room</Label>
                  <select
                    value={moveToRoomId}
                    onChange={e => { setMoveToRoomId(e.target.value); setMoveToDiffBed(0); }}
                    className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45]"
                  >
                    <option value="">Select room…</option>
                    {departmentList.map(dept => {
                      const deptRooms = moveableRooms.filter(r => locToDept.get(r.locationId) === dept);
                      if (deptRooms.length === 0) return null;
                      return (
                        <optgroup key={dept} label={`── ${dept} ──`}>
                          {deptRooms.map(r => {
                            const occ = getOccupancy(r.id);
                            return <option key={r.id} value={r.id}>{r.locationId} / {r.name} ({occ.occupied}/{occ.total})</option>;
                          })}
                        </optgroup>
                      );
                    })}
                  </select>
                </div>
                {moveToRoomId && (
                  <div>
                    <Label className="text-xs text-[#4A4A4A] mb-1 block">Select bed</Label>
                    <select
                      value={moveToDiffBed}
                      onChange={e => setMoveToDiffBed(Number(e.target.value))}
                      className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45]"
                    >
                      <option value={0}>Select bed…</option>
                      {diffRoomBedOptions.map(b => <option key={b.bedNumber} value={b.bedNumber}>Bed {b.bedNumber}</option>)}
                    </select>
                  </div>
                )}
              </div>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setMovePending(null)} className="border-[#D4CFC7] text-[#4A4A4A] h-9 text-sm">Cancel</Button>
            <Button
              onClick={handleConfirmMove}
              disabled={moveMode === 'same-room' ? !moveToBedNumber : (!moveToRoomId || !moveToDiffBed)}
              className="bg-[#2D5A45] hover:bg-[#234839] text-white h-9 text-sm"
            >
              Move Guest
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Manage Blocks Dialog ── */}
      <Dialog open={manageBlocksOpen} onOpenChange={o => { if (!o) { setManageBlocksOpen(false); setManageBlocksLocId(''); setEditingBlockId(null); setAddingBlock(false); setNewBlockName(''); } }}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle className="text-[#1A1A1A]">Manage Blocks</DialogTitle>
          </DialogHeader>
          <div className="py-2 space-y-4">
            {/* Location selector */}
            <div>
              <Label className="text-xs text-[#4A4A4A] mb-1 block">Location</Label>
              <select
                value={manageBlocksLocId}
                onChange={e => { setManageBlocksLocId(e.target.value); setEditingBlockId(null); setAddingBlock(false); setNewBlockName(''); }}
                className="w-full border border-[#D4CFC7] rounded-md px-3 py-2 text-sm text-[#1A1A1A] bg-white focus:outline-none focus:border-[#2D5A45] h-9"
              >
                <option value="">Select a location…</option>
                {departmentList.map(dept => {
                  const locs = (departments[dept] ?? []).map(ln => locationsList.find(l => l.name === ln)).filter(Boolean);
                  if (locs.length === 0) return null;
                  return (
                    <optgroup key={dept} label={`── ${dept} ──`}>
                      {locs.map(l => l && <option key={l.id} value={l.id}>{l.name}</option>)}
                    </optgroup>
                  );
                })}
              </select>
            </div>

            {manageBlocksLoc && (
              <>
                {manageableBlocks.length === 0 ? (
                  <p className="text-sm text-[#4A4A4A] text-center py-4">No blocks in {manageBlocksLoc.name} yet.</p>
                ) : (
                  <div className="rounded-lg border border-[#E8E3DB] overflow-hidden">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="bg-[#F5F0E8] border-b border-[#E8E3DB]">
                          <th className="text-left px-4 py-2.5 font-semibold text-[#4A4A4A] text-xs uppercase tracking-wider">Block Name</th>
                          <th className="text-left px-4 py-2.5 font-semibold text-[#4A4A4A] text-xs uppercase tracking-wider">Rooms</th>
                          <th className="px-4 py-2.5 text-right" />
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-[#E8E3DB]">
                        {manageableBlocks.map(block => {
                          const blockRoomCount = rooms.filter(r => r.blockId === block.id).length;
                          const isEditingThis = editingBlockId === block.id;
                          return (
                            <tr key={block.id} className="bg-white">
                              <td className="px-4 py-2.5">
                                {isEditingThis ? (
                                  <Input value={editingBlockName} onChange={e => setEditingBlockName(e.target.value)}
                                    className="border-[#D4CFC7] focus:border-[#2D5A45] h-8 text-sm w-full" autoFocus
                                    onKeyDown={e => { if (e.key === 'Enter') handleSaveEditBlock(block.id); if (e.key === 'Escape') setEditingBlockId(null); }} />
                                ) : (
                                  <span className="font-medium text-[#1A1A1A]">{block.name}</span>
                                )}
                              </td>
                              <td className="px-4 py-2.5 text-[#4A4A4A]">{blockRoomCount}</td>
                              <td className="px-4 py-2.5">
                                <div className="flex items-center gap-1 justify-end">
                                  {isEditingThis ? (
                                    <>
                                      <button onClick={() => handleSaveEditBlock(block.id)} className="text-xs text-[#2D5A45] font-medium hover:underline">Save</button>
                                      <button onClick={() => setEditingBlockId(null)} className="text-xs text-gray-400 hover:text-gray-600 ml-1">Cancel</button>
                                    </>
                                  ) : (
                                    <>
                                      <button onClick={() => { setEditingBlockId(block.id); setEditingBlockName(block.name); }} className="p-1.5 rounded text-[#4A4A4A] hover:bg-blue-50 hover:text-blue-600 transition-colors">
                                        <Pencil className="w-3.5 h-3.5" />
                                      </button>
                                      <button onClick={() => handleDeleteBlock(block)} disabled={blockRoomCount > 0}
                                        className="p-1.5 rounded text-[#4A4A4A] hover:bg-red-50 hover:text-red-600 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                                        title={blockRoomCount > 0 ? 'Remove all rooms first' : 'Delete block'}>
                                        <Trash2 className="w-3.5 h-3.5" />
                                      </button>
                                    </>
                                  )}
                                </div>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}

                {addingBlock ? (
                  <div className="flex items-center gap-2">
                    <Input value={newBlockName} onChange={e => setNewBlockName(e.target.value)} placeholder="Block name…"
                      className="border-[#D4CFC7] focus:border-[#2D5A45] h-9 text-sm flex-1" autoFocus
                      onKeyDown={e => { if (e.key === 'Enter') handleSaveNewBlock(); if (e.key === 'Escape') { setAddingBlock(false); setNewBlockName(''); } }} />
                    <Button onClick={handleSaveNewBlock} className="bg-[#2D5A45] hover:bg-[#234839] text-white h-9 px-4 text-sm">Add</Button>
                    <Button variant="outline" onClick={() => { setAddingBlock(false); setNewBlockName(''); }} className="border-[#D4CFC7] text-[#4A4A4A] h-9 text-sm">Cancel</Button>
                  </div>
                ) : (
                  <button onClick={() => setAddingBlock(true)} className="flex items-center gap-2 text-sm text-[#2D5A45] font-medium hover:underline">
                    <Plus className="w-4 h-4" /> Add Block
                  </button>
                )}
              </>
            )}
          </div>
          <DialogFooter>
            <Button onClick={() => setManageBlocksOpen(false)} className="bg-[#2D5A45] hover:bg-[#234839] text-white h-9 text-sm">Done</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Profile ── */}
      <ProfileDialog open={profileOpen} onClose={() => setProfileOpen(false)} />

      {/* ── Click-outside close for user menu ── */}
      {userMenuOpen && (
        <div className="fixed inset-0 z-10" onClick={() => setUserMenuOpen(false)} />
      )}
    </div>
  );
}
